## 1.	Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

matrix_sum = matrix_a + matrix_b

print("The sum of the two matrices is:", matrix_sum)

The sum of the two matrices is: [[11 13 15]
 [17 19 21]
 [23 25 27]]


## 2.	Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np

matrix_a = np.array([[1, 2, 3], [4, 5, 6]])

matrix_b = np.array([[7, 8], [9, 10], [11, 12]])

matrix_product = np.dot(matrix_a, matrix_b)

print("The product of the two matrices is:")
print(matrix_product)

The product of the two matrices is:
[[ 58  64]
 [139 154]]


## 3.	Write a Python Program to Transpose a Matrix?

In [3]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

transpose_matrix = matrix.transpose()

# Print the original and transposed matrix
print("Original matrix:")
print(matrix)
print("Transposed matrix:")
print(transpose_matrix)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [4]:
words = ['hello', 'world', 'python', 'programming', 'alphabetical']

sorted_words = sorted(words)
print("The words in alphabetical order are:", sorted_words)

The words in alphabetical order are: ['alphabetical', 'hello', 'programming', 'python', 'world']


## 5.	Write a Python Program to Remove Punctuation From a String?

In [7]:
string = "Hello, world! It's a beautiful day! :)"

punctuation_chars = ["'", '"', ",", ".", "!", "?", ";", ":"]

for char in punctuation_chars:
  string = string.replace(char, "")

print(string)

Hello world Its a beautiful day )
